SELECT
    lastIndexedDate::varchar AS lastindexeddate,
    relevanceScore::double AS relevancescore,
    accessibility::struct(classifications varchar[], accessroads varchar[], firestovepolicy varchar, trailerallowed bigint, adainfo varchar, trailermaxlength bigint, cellphoneinfo varchar, rvinfo varchar, additionalinfo varchar, rvallowed bigint, rvmaxlength bigint, wheelchairaccess varchar, internetinfo varchar) AS accessibility,
    numberOfSitesFirstComeFirstServe::bigint AS numberofsitesfirstcomefirstserve,
    numberOfSitesReservable::bigint AS numberofsitesreservable,
    multimedia::struct("type" varchar, url varchar, id varchar, title varchar)[] AS multimedia,
    weatherOverview::varchar AS weatheroverview,
    images::struct(url varchar, caption varchar, alttext varchar, title varchar, crops varchar[], credit varchar)[] AS images,
    addresses::struct("type" varchar, line2 varchar, line1 varchar, statecode varchar, countrycode varchar, line3 varchar, city varchar, provinceterritorycode varchar, postalcode varchar)[] AS addresses,
    campsites::struct(walkboatto bigint, tentonly bigint, horse bigint, rvonly bigint, electricalhookups bigint, "group" bigint, other bigint, totalsites bigint) AS campsites,
    fees::struct(description varchar, title varchar, "cost" double)[] AS fees,
    amenities::struct(foodstoragelockers varchar, potablewater varchar[], trashrecyclingcollection varchar, stafforvolunteerhostonsite varchar, iceavailableforsale varchar, amphitheater varchar, firewoodforsale varchar, dumpstation varchar, campstore varchar, cellphonereception varchar, showers varchar[], internetconnectivity varchar, laundry varchar, toilets varchar[]) AS amenities,
    isPassportStampLocation::bigint AS ispassportstamplocation,
    regulationsurl::varchar AS regulationsurl,
    directionsOverview::varchar AS directionsoverview,
    reservationInfo::varchar AS reservationinfo,
    passportStampLocationDescription::varchar AS passportstamplocationdescription,
    description::varchar AS description,
    directionsUrl::varchar AS directionsurl,
    geometryPoiId::varchar AS geometrypoiid,
    name::varchar AS name,
    operatingHours::struct("name" varchar, standardhours struct(friday varchar, sunday varchar, thursday varchar, tuesday varchar, saturday varchar, monday varchar, wednesday varchar), description varchar, exceptions struct(enddate date, "name" varchar, startdate date, exceptionhours struct(friday varchar, sunday varchar, thursday varchar, tuesday varchar, saturday varchar, monday varchar, wednesday varchar))[])[] AS operatinghours,
    reservationUrl::varchar AS reservationurl,
    audioDescription::varchar AS audiodescription,
    parkCode::varchar AS parkcode,
    latLong::varchar AS latlong,
    regulationsOverview::varchar AS regulationsoverview,
    passportStampImages::struct(url varchar, caption varchar, title varchar, alttext varchar, crops struct(url varchar, aspectratio double)[], description varchar, credit varchar)[] AS passportstampimages,
    latitude::double AS latitude,
    url::varchar AS url,
    longitude::double AS longitude,
    contacts::struct(emailaddresses struct(emailaddress varchar, description varchar)[], phonenumbers struct("extension" bigint, "type" varchar, description varchar, phonenumber varchar)[]) AS contacts,
    id::varchar AS id
FROM {{ source('raw_nps_api', 'campgrounds') }}